# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import robot_server_pb2 as robot__server__pb2


class RobotServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetState = channel.unary_unary(
        '/robot_server.RobotServer/GetState',
        request_serializer=robot__server__pb2.State.SerializeToString,
        response_deserializer=robot__server__pb2.State.FromString,
        )
    self.SetState = channel.unary_unary(
        '/robot_server.RobotServer/SetState',
        request_serializer=robot__server__pb2.State.SerializeToString,
        response_deserializer=robot__server__pb2.Success.FromString,
        )
    self.SendAction = channel.unary_unary(
        '/robot_server.RobotServer/SendAction',
        request_serializer=robot__server__pb2.Action.SerializeToString,
        response_deserializer=robot__server__pb2.Success.FromString,
        )


class RobotServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetState(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendAction(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RobotServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetState': grpc.unary_unary_rpc_method_handler(
          servicer.GetState,
          request_deserializer=robot__server__pb2.State.FromString,
          response_serializer=robot__server__pb2.State.SerializeToString,
      ),
      'SetState': grpc.unary_unary_rpc_method_handler(
          servicer.SetState,
          request_deserializer=robot__server__pb2.State.FromString,
          response_serializer=robot__server__pb2.Success.SerializeToString,
      ),
      'SendAction': grpc.unary_unary_rpc_method_handler(
          servicer.SendAction,
          request_deserializer=robot__server__pb2.Action.FromString,
          response_serializer=robot__server__pb2.Success.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'robot_server.RobotServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
