# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot_server.proto',
  package='robot_server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12robot_server.proto\x12\x0crobot_server\"\x1a\n\x07Success\x12\x0f\n\x07success\x18\x01 \x01(\x08\")\n\x06\x41\x63tion\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x02\x12\x0f\n\x07success\x18\x02 \x01(\x08\"T\n\x05State\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x03(\x02\x12\x17\n\x0freference_frame\x18\x03 \x01(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x32\xbc\x01\n\x0bRobotServer\x12\x36\n\x08GetState\x12\x13.robot_server.State\x1a\x13.robot_server.State\"\x00\x12\x38\n\x08SetState\x12\x13.robot_server.State\x1a\x15.robot_server.Success\"\x00\x12;\n\nSendAction\x12\x14.robot_server.Action\x1a\x15.robot_server.Success\"\x00\x62\x06proto3'
)




_SUCCESS = _descriptor.Descriptor(
  name='Success',
  full_name='robot_server.Success',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='robot_server.Success.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=62,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='robot_server.Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='robot_server.Action.action', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='robot_server.Action.success', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=105,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='robot_server.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_name', full_name='robot_server.State.model_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state', full_name='robot_server.State.state', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reference_frame', full_name='robot_server.State.reference_frame', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='success', full_name='robot_server.State.success', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=191,
)

DESCRIPTOR.message_types_by_name['Success'] = _SUCCESS
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
DESCRIPTOR.message_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Success = _reflection.GeneratedProtocolMessageType('Success', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESS,
  '__module__' : 'robot_server_pb2'
  # @@protoc_insertion_point(class_scope:robot_server.Success)
  })
_sym_db.RegisterMessage(Success)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'robot_server_pb2'
  # @@protoc_insertion_point(class_scope:robot_server.Action)
  })
_sym_db.RegisterMessage(Action)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'robot_server_pb2'
  # @@protoc_insertion_point(class_scope:robot_server.State)
  })
_sym_db.RegisterMessage(State)



_ROBOTSERVER = _descriptor.ServiceDescriptor(
  name='RobotServer',
  full_name='robot_server.RobotServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=194,
  serialized_end=382,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetState',
    full_name='robot_server.RobotServer.GetState',
    index=0,
    containing_service=None,
    input_type=_STATE,
    output_type=_STATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetState',
    full_name='robot_server.RobotServer.SetState',
    index=1,
    containing_service=None,
    input_type=_STATE,
    output_type=_SUCCESS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendAction',
    full_name='robot_server.RobotServer.SendAction',
    index=2,
    containing_service=None,
    input_type=_ACTION,
    output_type=_SUCCESS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROBOTSERVER)

DESCRIPTOR.services_by_name['RobotServer'] = _ROBOTSERVER

# @@protoc_insertion_point(module_scope)
